/*
 * DispositorTestFrame.java
 *
 * Created on 2008/10/27, 0:27
 */

package to.tetramorph.starbase.util;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import javax.swing.JPanel;

/**
 * ディスポジターグラフをテスト表示する。廃止予定。
 * @author  大澤義鷹
 */
public class DispositorTestFrame extends javax.swing.JFrame {
    Dispositor dispositor;
    int [] testdata = { 5,1,2,3,6,4,7,8,9,11 };
    /** Creates new form DispositorTestFrame */
    GraphPane gp;
    public DispositorTestFrame() {
        initComponents();
        setSize(250,250);
        gp = new GraphPane();
        add( gp );
        dispositor = new Dispositor();
    }
    
    class GraphPane extends JPanel {
        @Override
        public void paintComponent( Graphics g ) {
            BufferedImage img = dispositor.getGraph( testdata,getWidth(),Dispositor.MODERN );
            g.drawImage( img, 0, 0, this );
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getContentPane().setLayout(new java.awt.GridLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        gp.repaint();
    }//GEN-LAST:event_formComponentResized
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DispositorTestFrame frame = new DispositorTestFrame();
                frame.setLocationRelativeTo( null );
                frame.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
