/*
 * NatalCalcConfPanel.java
 *
 * Created on 2007/04/01, 8:01
 */

package to.tetramorph.starbase.chartmodule;

import java.util.List;
import to.tetramorph.starbase.lib.AspectType;
import to.tetramorph.starbase.widget.CustomizePanel;
import to.tetramorph.util.Preference;
import static to.tetramorph.starbase.lib.Const.*;
import to.tetramorph.starbase.lib.Const;
/**
 * ネイタル円プラグイン用の計算設定パネル
 * <pre>
 * set/get可能なPreference値は次の通り。
 * NatalBodys       使用天体IDの列挙(0,1,2,,,)
 * NatalAspectBodys アスペクト検出する天体IDの列挙(0,1,2,,,)
 * UseAspects       使用するアスペクトの定義。(アスペクト名,タイトオーブ,ルーズオーブ,以降繰り返し)
 * 
 * getPropertyで取得できるが、Preferenceなので、int[]やAspectType[]として取得可能。
 * </pre>
 * @author 大澤義鷹
 */
public class NatalCalcConfPanel extends CustomizePanel {
//  //使用するアスペクトのリスト
//  private static final AspectType [] defAspects = {
//    new AspectType(CONJUNCTION,4,8),
//    new AspectType(SEXTILE,3,6),
//    new AspectType(SQUARE,4,8),
//    new AspectType(TRINE,4,8),
//    new AspectType(OPPOSITION,4,8),
//    new AspectType(QUINCUNX,3,6),
//  };
  //デフォルトのアスペクト設定 ( ｱｽﾍﾟｸﾄID,ﾀｲﾄｵｰﾌﾞ,ﾙｰｽﾞｵｰﾌﾞ )
  private static final String defaultAspects =
    "0,4,8," +  //CONJUNCTION
    "1,3,6," +   //SEXTILE
    "2,4,8," +   //SQUARE
    "3,4,8," +   //TRINE
    "4,4,8," +   //OPPOSITION
    "5,3,6";    //QUINCUNX
  
  /** 
   * オブジェクトを作成する。
   */
  public NatalCalcConfPanel() {
    initComponents();
    // 使用天体とアスペクト検出天体のパネルを同期させる設定
    planetsSelectionPanel1.setSlavePanel( planetsSelectionPanel2 );
    // ｱｽﾍﾟｸﾄのﾃﾞﾌｫﾙﾄ値を設定する。
    aspectTypePanel1.setSelected( defaultAspects );
  }

  public Preference getPreference(Preference pref) {
    pref.setProperty("NatalBodys",planetsSelectionPanel1.getSelected());
    pref.setProperty("NatalAspectBodys",planetsSelectionPanel2.getSelected());
    pref.setProperty("UseAspects",aspectTypePanel1.getSelected());
    return pref;
  }

  public void setPreference(Preference pref) {
    planetsSelectionPanel1.setSelected(pref.getProperty("NatalBodys"));
    planetsSelectionPanel2.setSelected(pref.getProperty("NatalAspectBodys"));
    aspectTypePanel1.setSelected(pref.getProperty("UseAspects"));
  }
//  /**
//   * 使用する天体のリストを返す。
//   */
//  public List<Integer> getUseBodyList() {
//    return planetsSelectionPanel1.getSelectedList();
//  }
//  public int [] getBodyIDs() {
//    return planetsSelectionPanel1.getBodyIDs();
//  }
//  /**
//   * アスペクトを検出する天体のリストを返す。
//   */
//  public List<Integer> getNatalAspectBodys() {
//    return planetsSelectionPanel2.getSelectedList();
//  }
//  /**
//   * アスペクトを検出する天体のリストを返す。
//   */
//  public int [] getAspectBodyIDs() {
//    return planetsSelectionPanel2.getBodyIDs();
//  }
//  /**
//   * アスペクトタイプのリストを返す。
//   */
//  public AspectType [] getAspectTypes() {
//    return aspectTypePanel1.getAspectTypes();
//  }
  /**
   * このパネルの設定が正しく行われている状態ならtrue。フィールドに以上な値が
   * 入力されている場合などはfalseを返す。
   * @param errmsg 要素数1の文字配列を与える。戻り値がfalseの場合エラーメッセージが参照書き込みされる。
   */
  public boolean isCorrect(String [] errmsg) {
    AspectType [] atype = aspectTypePanel1.getAspectTypes();
    for(int i=0; i<atype.length; i++) {
      if((atype[i].tightOrb <= 0 || atype[i].looseOrb <= 0) ||
         (atype[i].tightOrb >= atype[i].looseOrb) ) {
        errmsg[0] = "アスペクト\"" + Const.ASPECT_NAMES[i] + "\"のオーブの設定値が未入力か異常です。";
        return false;
      }
    }
    return true;
  }
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;

    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    planetsSelectionPanel1 = new to.tetramorph.starbase.widget.PlanetsSelectionPanel();
    jPanel2 = new javax.swing.JPanel();
    planetsSelectionPanel2 = new to.tetramorph.starbase.widget.PlanetsSelectionPanel();
    jSeparator1 = new javax.swing.JSeparator();
    aspectTypePanel1 = new to.tetramorph.starbase.widget.AspectTypePanel();

    setLayout(new java.awt.BorderLayout());

    jPanel1.setLayout(new java.awt.BorderLayout());

    jPanel1.setMinimumSize(new java.awt.Dimension(350, 100));
    jPanel1.setPreferredSize(new java.awt.Dimension(350, 100));
    planetsSelectionPanel1.setMinimumSize(null);
    jPanel1.add(planetsSelectionPanel1, java.awt.BorderLayout.CENTER);

    jTabbedPane1.addTab("\u4f7f\u7528\u5929\u4f53", jPanel1);

    jPanel2.setLayout(new java.awt.GridBagLayout());

    planetsSelectionPanel2.setTitle("\u30a2\u30b9\u30da\u30af\u30c8\u3092\u691c\u51fa\u3059\u308b\u5929\u4f53");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel2.add(planetsSelectionPanel2, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(9, 0, 9, 0);
    jPanel2.add(jSeparator1, gridBagConstraints);

    jPanel2.add(aspectTypePanel1, new java.awt.GridBagConstraints());

    jTabbedPane1.addTab("\u30a2\u30b9\u30da\u30af\u30c8", jPanel2);

    add(jTabbedPane1, java.awt.BorderLayout.CENTER);

  }// </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private to.tetramorph.starbase.widget.AspectTypePanel aspectTypePanel1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JTabbedPane jTabbedPane1;
  private to.tetramorph.starbase.widget.PlanetsSelectionPanel planetsSelectionPanel1;
  private to.tetramorph.starbase.widget.PlanetsSelectionPanel planetsSelectionPanel2;
  // End of variables declaration//GEN-END:variables

  
}
