/*
 * SplitTest.java
 *
 * Created on 2007/10/26, 0:27
 */

package split;

/**
 * JSplitPaneのデバイダーを自分の好みのものにカスタマイズする実験。
 *
 * @author  大澤義鷹
 */
public class SplitTest extends javax.swing.JFrame {
  SplitPane sp = new SplitPane();
  /** Creates new form SplitTest */
  public SplitTest() {
    initComponents();
    add(sp);
    sp.setLeftComponent(new TreeOfLifePanel());
    sp.setDividerSize(0);
    sp.setRightComponent(null);
    pack();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    getContentPane().setLayout(new java.awt.GridLayout());

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    pack();
  }// </editor-fold>//GEN-END:initComponents
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new SplitTest().setVisible(true);
      }
    });
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
  
}
