/*
 * VerticalButtonTest.java
 *
 * Created on 2007/11/13, 0:59
 */

package vbutton;

import java.awt.Container;
import java.awt.FlowLayout;
import javax.swing.Icon;
import to.tetramorph.starbase.test.*;
import to.tetramorph.util.IconLoader;

/**
 *
 * @author  ‘åàV‹`‘é
 */
public class VerticalButtonTest extends javax.swing.JFrame {
  Icon femaleIcon = IconLoader.getImageIcon("/resources/List.female.png");
  
  /** Creates new form VerticalButtonTest */
  public VerticalButtonTest() {
    initComponents();
    setLayout(new FlowLayout());
    Container c = getContentPane();
    VerticalJButton button = new VerticalJButton("‘åàV‹`‘é");
    button.setIcon(femaleIcon);
    c.add(new VerticalJButton("HogeHoge"));
    c.add( button );
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );
    pack();
  }// </editor-fold>//GEN-END:initComponents
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VerticalButtonTest().setVisible(true);
      }
    });
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
  
}
