/*
 * BodyMoverDialog.java
 *
 * Created on 2007/07/14, 11:28
 */

package to.tetramorph.starbase.chartparts;

/**
 * 天体を移動させることで、時間を移動させる計算機だが、GUIだけ作って中身は実装
 * していない。
 * @author  大澤義鷹
 */
public class BodyMoverDialog extends javax.swing.JDialog {
  
  /** Creates new form BodyMoverDialog */
  public BodyMoverDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JLabel aapgLabel;
        javax.swing.JLabel acLabel;
        javax.swing.JLabel apgLabel;
        javax.swing.JLabel avtxLabel;
        javax.swing.JLabel celLabel;
        javax.swing.JLabel chiLabel;
        javax.swing.JLabel dcLabel;
        javax.swing.JLabel earLabel;
        java.awt.GridBagConstraints gridBagConstraints;
        javax.swing.JLabel icLabel;
        javax.swing.JLabel jLabel8;
        javax.swing.JLabel jLabel9;
        javax.swing.JPanel jPanel1;
        javax.swing.JPanel jPanel3;
        javax.swing.JLabel junLabel;
        javax.swing.JLabel jupLabel;
        javax.swing.JLabel marLabel;
        javax.swing.JLabel mcLabel;
        javax.swing.JLabel merLabel;
        javax.swing.JLabel monLabel;
        javax.swing.JLabel nepLabel;
        javax.swing.JLabel nodLabel;
        javax.swing.JLabel palLabel;
        javax.swing.JLabel phoLabel;
        javax.swing.JLabel pluLabel;
        javax.swing.JLabel satLabel;
        javax.swing.JLabel sunLabel;
        javax.swing.JLabel uraLabel;
        javax.swing.JLabel venLabel;
        javax.swing.JLabel vesLabel;
        javax.swing.JLabel vtxLabel;

        buttonPanel = new javax.swing.JPanel();
        sunLabel = new javax.swing.JLabel();
        monLabel = new javax.swing.JLabel();
        merLabel = new javax.swing.JLabel();
        venLabel = new javax.swing.JLabel();
        marLabel = new javax.swing.JLabel();
        jupLabel = new javax.swing.JLabel();
        satLabel = new javax.swing.JLabel();
        uraLabel = new javax.swing.JLabel();
        nepLabel = new javax.swing.JLabel();
        pluLabel = new javax.swing.JLabel();
        acLabel = new javax.swing.JLabel();
        mcLabel = new javax.swing.JLabel();
        dcLabel = new javax.swing.JLabel();
        icLabel = new javax.swing.JLabel();
        nodLabel = new javax.swing.JLabel();
        apgLabel = new javax.swing.JLabel();
        earLabel = new javax.swing.JLabel();
        chiLabel = new javax.swing.JLabel();
        phoLabel = new javax.swing.JLabel();
        celLabel = new javax.swing.JLabel();
        palLabel = new javax.swing.JLabel();
        junLabel = new javax.swing.JLabel();
        vesLabel = new javax.swing.JLabel();
        aapgLabel = new javax.swing.JLabel();
        vtxLabel = new javax.swing.JLabel();
        avtxLabel = new javax.swing.JLabel();
        snodLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        buttonPanel.setLayout(new java.awt.GridBagLayout());

        sunLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/sun.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 3, 1);
        buttonPanel.add(sunLabel, gridBagConstraints);

        monLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/mon.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 3, 1);
        buttonPanel.add(monLabel, gridBagConstraints);

        merLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/mer.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 3, 1);
        buttonPanel.add(merLabel, gridBagConstraints);

        venLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/ven.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 3, 1);
        buttonPanel.add(venLabel, gridBagConstraints);

        marLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/mar.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 3, 1);
        buttonPanel.add(marLabel, gridBagConstraints);

        jupLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/jup.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 3, 1);
        buttonPanel.add(jupLabel, gridBagConstraints);

        satLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/sat.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 3, 1);
        buttonPanel.add(satLabel, gridBagConstraints);

        uraLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/ura.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 3, 1);
        buttonPanel.add(uraLabel, gridBagConstraints);

        nepLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/nep.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 3, 1);
        buttonPanel.add(nepLabel, gridBagConstraints);

        pluLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/plu.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 3, 1);
        buttonPanel.add(pluLabel, gridBagConstraints);

        acLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/ac.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 3, 1);
        buttonPanel.add(acLabel, gridBagConstraints);

        mcLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/mc.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 3, 1);
        buttonPanel.add(mcLabel, gridBagConstraints);

        dcLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/dc.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 3, 1);
        buttonPanel.add(dcLabel, gridBagConstraints);

        icLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/ic.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 3, 1);
        buttonPanel.add(icLabel, gridBagConstraints);

        nodLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/nod.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 3, 1);
        buttonPanel.add(nodLabel, gridBagConstraints);

        apgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/apg.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 3, 1);
        buttonPanel.add(apgLabel, gridBagConstraints);

        earLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/ear.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 3, 1);
        buttonPanel.add(earLabel, gridBagConstraints);

        chiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/chi.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 3, 1);
        buttonPanel.add(chiLabel, gridBagConstraints);

        phoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/pho.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 3, 1);
        buttonPanel.add(phoLabel, gridBagConstraints);

        celLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/cer.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 3, 1);
        buttonPanel.add(celLabel, gridBagConstraints);

        palLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/pal.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 3, 1);
        buttonPanel.add(palLabel, gridBagConstraints);

        junLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/jun.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 3, 1);
        buttonPanel.add(junLabel, gridBagConstraints);

        vesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/ves.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 3, 1);
        buttonPanel.add(vesLabel, gridBagConstraints);

        aapgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/aapg.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 3, 1);
        buttonPanel.add(aapgLabel, gridBagConstraints);

        vtxLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/v.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 3, 1);
        buttonPanel.add(vtxLabel, gridBagConstraints);

        avtxLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/av.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 3, 1);
        buttonPanel.add(avtxLabel, gridBagConstraints);

        snodLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/symbols/snd.gif")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 3, 1);
        buttonPanel.add(snodLabel, gridBagConstraints);

        jButton1.setText("\uff0b");
        jButton1.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton1, gridBagConstraints);

        jButton2.setText("\uff0b");
        jButton2.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton2, gridBagConstraints);

        jButton3.setText("\uff0b");
        jButton3.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton3, gridBagConstraints);

        jButton4.setText("\uff0b");
        jButton4.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton4, gridBagConstraints);

        jButton5.setText("\uff0b");
        jButton5.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton5, gridBagConstraints);

        jButton6.setText("\uff0b");
        jButton6.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton6, gridBagConstraints);

        jButton7.setText("\uff0b");
        jButton7.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton7, gridBagConstraints);

        jButton8.setText("\uff0b");
        jButton8.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton8, gridBagConstraints);

        jButton9.setText("\uff0b");
        jButton9.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton9, gridBagConstraints);

        jButton10.setText("\uff0b");
        jButton10.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton10, gridBagConstraints);

        jButton11.setText("\uff0b");
        jButton11.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton11, gridBagConstraints);

        jButton12.setText("\uff0b");
        jButton12.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton12, gridBagConstraints);

        jButton13.setText("\uff0b");
        jButton13.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton13, gridBagConstraints);

        jButton14.setText("\uff0b");
        jButton14.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton14, gridBagConstraints);

        jButton15.setText("\uff0b");
        jButton15.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton15, gridBagConstraints);

        jButton16.setText("\uff0d");
        jButton16.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton16, gridBagConstraints);

        jButton17.setText("\uff0d");
        jButton17.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton17, gridBagConstraints);

        jButton18.setText("\uff0d");
        jButton18.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton18, gridBagConstraints);

        jButton19.setText("\uff0d");
        jButton19.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton19, gridBagConstraints);

        jButton20.setText("\uff0d");
        jButton20.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton20, gridBagConstraints);

        jButton21.setText("\uff0d");
        jButton21.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton21, gridBagConstraints);

        jButton22.setText("\uff0d");
        jButton22.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton22, gridBagConstraints);

        jButton23.setText("\uff0d");
        jButton23.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton23, gridBagConstraints);

        jButton24.setText("\uff0d");
        jButton24.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton24, gridBagConstraints);

        jButton25.setText("\uff0d");
        jButton25.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton25, gridBagConstraints);

        jButton26.setText("\uff0d");
        jButton26.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton26, gridBagConstraints);

        jButton27.setText("\uff0d");
        jButton27.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton27, gridBagConstraints);

        jButton28.setText("\uff0d");
        jButton28.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton28, gridBagConstraints);

        jButton29.setText("\uff0d");
        jButton29.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton29, gridBagConstraints);

        jButton30.setText("\uff0d");
        jButton30.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton30, gridBagConstraints);

        jButton31.setText("\uff0d");
        jButton31.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton31, gridBagConstraints);

        jButton32.setText("\uff0b");
        jButton32.setActionCommand("\uff0d");
        jButton32.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton32, gridBagConstraints);

        jButton33.setText("\uff0b");
        jButton33.setActionCommand("\uff0d");
        jButton33.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton33, gridBagConstraints);

        jButton34.setText("\uff0b");
        jButton34.setActionCommand("\uff0d");
        jButton34.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton34, gridBagConstraints);

        jButton35.setText("\uff0b");
        jButton35.setActionCommand("\uff0d");
        jButton35.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton35, gridBagConstraints);

        jButton36.setText("\uff0b");
        jButton36.setActionCommand("\uff0d");
        jButton36.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton36, gridBagConstraints);

        jButton37.setText("\uff0b");
        jButton37.setActionCommand("\uff0d");
        jButton37.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton37, gridBagConstraints);

        jButton38.setText("\uff0b");
        jButton38.setActionCommand("\uff0d");
        jButton38.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton38, gridBagConstraints);

        jButton39.setText("\uff0b");
        jButton39.setActionCommand("\uff0d");
        jButton39.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton39, gridBagConstraints);

        jButton40.setText("\uff0b");
        jButton40.setActionCommand("\uff0d");
        jButton40.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton40, gridBagConstraints);

        jButton41.setText("\uff0b");
        jButton41.setActionCommand("\uff0d");
        jButton41.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton41, gridBagConstraints);

        jButton42.setText("\uff0d");
        jButton42.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton42, gridBagConstraints);

        jButton43.setText("\uff0b");
        jButton43.setActionCommand("\uff0d");
        jButton43.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton43, gridBagConstraints);

        jButton44.setText("\uff0d");
        jButton44.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton44, gridBagConstraints);

        jButton45.setText("\uff0d");
        jButton45.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton45, gridBagConstraints);

        jButton46.setText("\uff0d");
        jButton46.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton46, gridBagConstraints);

        jButton47.setText("\uff0d");
        jButton47.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton47, gridBagConstraints);

        jButton48.setText("\uff0d");
        jButton48.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton48, gridBagConstraints);

        jButton49.setText("\uff0d");
        jButton49.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton49, gridBagConstraints);

        jButton50.setText("\uff0d");
        jButton50.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton50, gridBagConstraints);

        jButton51.setText("\uff0d");
        jButton51.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton51, gridBagConstraints);

        jButton52.setText("\uff0d");
        jButton52.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton52, gridBagConstraints);

        jButton53.setText("\uff0d");
        jButton53.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton53, gridBagConstraints);

        jButton54.setText("\uff0b");
        jButton54.setActionCommand("\uff0d");
        jButton54.setMargin(new java.awt.Insets(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        buttonPanel.add(jButton54, gridBagConstraints);

        jLabel1.setText("\u5929\u4f53");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 3, 3);
        buttonPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("\u672a\u6765");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 3);
        buttonPanel.add(jLabel2, gridBagConstraints);

        jLabel3.setText("\u904e\u53bb");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 3);
        buttonPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setText("\u5929\u4f53");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 1, 3, 3);
        buttonPanel.add(jLabel4, gridBagConstraints);

        jLabel5.setText("\u672a\u6765");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 3);
        buttonPanel.add(jLabel5, gridBagConstraints);

        jLabel6.setText("\u904e\u53bb");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 3);
        buttonPanel.add(jLabel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(buttonPanel, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "\u30cd\u30a4\u30bf\u30eb", "\u30d7\u30ed\u30b0\u30ec\u30b9", "\u30c8\u30e9\u30f3\u30b8\u30c3\u30c8" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jComboBox1, gridBagConstraints);

        jLabel7.setText("\u79fb\u52d5\u5bfe\u8c61");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        jPanel1.add(jLabel7, gridBagConstraints);

        jPanel3.add(jPanel1, new java.awt.GridBagConstraints());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel8.setText("\u79fb\u52d5\u30b9\u30c6\u30c3\u30d7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        jPanel2.add(jLabel8, gridBagConstraints);

        jSpinner1.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel2.add(jSpinner1, new java.awt.GridBagConstraints());

        jLabel9.setText("\u5ea6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        jPanel2.add(jLabel9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel3.add(jPanel2, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jRadioButton1.setText("\u304d\u3063\u3061\u308an.00\u5ea6\u306b\u5165\u308b\u3088\u3046\u306b\u8a08\u7b97");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        jPanel4.add(jRadioButton1, gridBagConstraints);

        jRadioButton2.setText("\u4eca\u306e\u4f4d\u7f6e\u306bn\u5ea6\u52a0\u3048\u308b\u3088\u3046\u306b\u8a08\u7b97");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(jRadioButton2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel3.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 0);
        getContentPane().add(jPanel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new BodyMoverDialog(new javax.swing.JFrame(), true).setVisible(true);
      }
    });
  }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel snodLabel;
    // End of variables declaration//GEN-END:variables
  
}
