/*
 * InstallerFrame.java
 * Created on 2011/07/18, 14:32:13.
 */

/*
 * InstallerFrame.java
 *
 * Created on 2011/07/18, 14:32:13
 */
package amateru_installer;

import java.awt.CardLayout;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;

/**
 * インストーラのメインフレームで、この中にライセンス確認パネルや、フォルダ選択パネル、
 * 進行表示パネルなどが集約されている。カードレイアウトでそれらのパネルを切り替える。
 * Mainクラスがこのフレームを作り可視化する。
 *
 * @author ohsawa
 */
class InstallerFrame extends javax.swing.JFrame {
    /** Creates new form InstallerFrame */
    public InstallerFrame() {
        initComponents();
        List<Image> icons = new ArrayList<Image>();
        icons.add(ResourceLoader.getImage("/resources/niwatori16.png"));
        icons.add(ResourceLoader.getImage("/resources/niwatori32.png"));
        this.setIconImages( icons );
        this.setLocationRelativeTo(null);
    }
    /**
     * このフレームの中にある子のパネルに親の参照を教える。強い集約構造を作ってしまう
     * やり方だが、小さなアプリではスマートなやり方。コンストラクタの中に書いても
     * よいのだが、それは推奨されないためメソッドを用意した。
     */
    void setup() {
        licensePanel.frame = this;
        selectFolderPanel.frame = this;
        installPanel.frame = this;
    }

    /**
     * 子のパネルを選択表示する。
     * @param name "license"はライセンス同意パネル。"select"はインストール先
     * フォルダの設定画面。
     */
    public void selectCard( String name ) {
        ((CardLayout)cardPanel.getLayout()).show(cardPanel, name);
        if ( name.equals("install")) {
            installPanel.start();
        }
    }

    /**
     * インストーラを終了する。
     * 「中止」ボタンなどから呼ばれる。
     */
    void exit() {
        dispose();
        System.exit(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();
        licensePanel = new amateru_installer.LicensePanel();
        selectFolderPanel = new amateru_installer.SelectFolderPanel();
        installPanel = new amateru_installer.InstallPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("アマテルのインストール");
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        cardPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 1, 20));
        cardPanel.setPreferredSize(new java.awt.Dimension(600, 550));
        cardPanel.setLayout(new java.awt.CardLayout());
        cardPanel.add(licensePanel, "license");
        cardPanel.add(selectFolderPanel, "select");
        cardPanel.add(installPanel, "install");

        getContentPane().add(cardPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPanel;
    private amateru_installer.InstallPanel installPanel;
    private amateru_installer.LicensePanel licensePanel;
    private amateru_installer.SelectFolderPanel selectFolderPanel;
    // End of variables declaration//GEN-END:variables
}
