/*
 * LicensePanel.java
 * Created on 2011/07/18, 14:06:26.
 */

/*
 * LicensePanel.java
 *
 * Created on 2011/07/18, 14:06:26
 */
package amateru_installer;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JRadioButton;

/**
 * ライセンスを表示して同意を求めるパネル。
 * 同意しなければ先に進めない仕組み。
 * @author ohsawa
 */
class LicensePanel extends javax.swing.JPanel {
    InstallerFrame frame = null;

    /** Creates new form LicensePanel */
    public LicensePanel() {
        initComponents();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                String text = ResourceLoader.getText("/resources/GPL.txt", "UTF-8");
                textArea.setText( text );
                textArea.setCaretPosition(0);
            }
        });
        ActionListener a = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt ) {
                String c = ((JRadioButton)evt.getSource()).getActionCommand();
                nextButton.setEnabled( c.equals("Y") );
            }
        };
        licenseRadioButton1.addActionListener(a);
        licenseRadioButton2.addActionListener(a);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        licenseRadioButton1 = new javax.swing.JRadioButton();
        licenseRadioButton2 = new javax.swing.JRadioButton();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        lic_abortButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();

        buttonGroup1.add( licenseRadioButton1 );
        buttonGroup1.add( licenseRadioButton2 );

        setLayout(new java.awt.BorderLayout(0, 8));

        jLabel1.setText("ライセンスの確認");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        textArea.setColumns(20);
        textArea.setEditable(false);
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        scrollPane.setViewportView(textArea);

        add(scrollPane, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        licenseRadioButton1.setSelected(true);
        licenseRadioButton1.setText("ライセンスに同意しません");
        jPanel1.add(licenseRadioButton1, new java.awt.GridBagConstraints());

        licenseRadioButton2.setText("ライセンスに同意します");
        licenseRadioButton2.setActionCommand("Y");
        jPanel1.add(licenseRadioButton2, new java.awt.GridBagConstraints());

        lic_abortButton.setMnemonic('N');
        lic_abortButton.setText("中止(N)");
        lic_abortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lic_abortButtonActionPerformed(evt);
            }
        });
        jPanel2.add(lic_abortButton);

        nextButton.setMnemonic('Y');
        nextButton.setText("次へ(Y)");
        nextButton.setEnabled(false);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        jPanel2.add(nextButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jPanel2, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        frame.selectCard("select");
    }//GEN-LAST:event_nextButtonActionPerformed

    private void lic_abortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lic_abortButtonActionPerformed
        frame.exit();
    }//GEN-LAST:event_lic_abortButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton lic_abortButton;
    private javax.swing.JRadioButton licenseRadioButton1;
    private javax.swing.JRadioButton licenseRadioButton2;
    private javax.swing.JButton nextButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
