/*
 * BodyListPanel.java
 *
 * Created on 2007/07/05, 23:23
 */

package to.tetramorph.starbase.chartparts;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.List;
import to.tetramorph.starbase.lib.Body;

/**
 * 天体位置のリストを表示するパネル(実験したが使い物にならず廃止)
 * @author  大澤義鷹
 */
public class BodyListPanel extends javax.swing.JPanel {
  PositionReporter reporter = new PositionReporter();
  /** Creates new form BodyListPanel */
  public BodyListPanel() {
    initComponents();
  }
  public void paintComponent(Graphics graphics) {
    super.paintComponent(graphics);
    Graphics2D g = (Graphics2D)graphics;
    g.setRenderingHint(
      RenderingHints.KEY_ANTIALIASING,
      RenderingHints.VALUE_ANTIALIAS_ON);
    Dimension size = getSize();
    double width = size.getWidth();
    double height = size.getHeight();
    reporter.draw(g,0,0,width,height);
  }
  public void setBodyList(List<Body> bodyList) {
    reporter.setBodyList(bodyList);
  }
  public void setCusps(List<Body> cuspList) {
    reporter.setCuspList(cuspList);
  }
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(0, 300, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
  
}
