/*
 * MotifFrame.java
 *
 * Created on 2007/12/13, 5:47
 */

package test;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JMenu;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author  ‘åàV‹`‘é
 */
public class MotifFrame extends javax.swing.JFrame {
    
    /** Creates new form MotifFrame */
    public MotifFrame() {
        initComponents();
        menuBar.add(createLookAndFeelMenu());
    }
    ButtonGroup lafButtonGroup = new ButtonGroup();
    private JMenu createLookAndFeelMenu() {
        UIManager.LookAndFeelInfo[] lafs = 
            UIManager.getInstalledLookAndFeels();
        JRadioButtonMenuItem [] menus = new JRadioButtonMenuItem[ lafs.length ];
        JMenu menu = new JMenu("LaF");
        String defaultClass = UIManager.getCrossPlatformLookAndFeelClassName();
        for ( int i=0; i<lafs.length; i++ ) {
            String className = lafs[i].getClassName();
            menus[i] = new JRadioButtonMenuItem( lafs[i].getName() );
            menus[i].setActionCommand( className );
            if ( className.equals( defaultClass ))
                menus[i].setSelected( true );
            menus[i].addActionListener( new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    String laf = evt.getActionCommand();
                    try {
                        UIManager.setLookAndFeel(laf);
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                    SwingUtilities.updateComponentTreeUI( MotifFrame.this );
                }
            });
            lafButtonGroup.add( menus[i] );
            menu.add(menus[i]);
        }
        return menu;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        zoneButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        zoneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/jisaNormal.png")));
        zoneButton.setMnemonic('Z');
        zoneButton.setToolTipText("\u4e16\u754c\u306e\u30bf\u30a4\u30e0\u30be\u30fc\u30f3\u3092\u9078\u629e");
        zoneButton.setBorderPainted(false);
        zoneButton.setContentAreaFilled(false);
        zoneButton.setFocusPainted(false);
        zoneButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        zoneButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/jisaPressed.png")));
        zoneButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/jisaRollover.png")));
        zoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoneButtonActionPerformed(evt);
            }
        });

        getContentPane().add(zoneButton);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/jisaNormal.png")));
        jButton1.setMnemonic('Z');
        jButton1.setToolTipText("\u4e16\u754c\u306e\u30bf\u30a4\u30e0\u30be\u30fc\u30f3\u3092\u9078\u629e");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/jisaPressed.png")));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/jisaRollover.png")));
        getContentPane().add(jButton1);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoneButtonActionPerformed
    }//GEN-LAST:event_zoneButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                try {
//                        UIManager.setLookAndFeel(
//                             "com.sun.java.swing.plaf.motif.MotifLookAndFeel");
//                } catch (Exception e) {
//                        e.printStackTrace();}                
                new MotifFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton zoneButton;
    // End of variables declaration//GEN-END:variables
    
}
