/*
 * NewJFrame2.java
 *
 * Created on 2007/09/29, 7:29
 */

package to.tetramorph.starbase.chartmodule;

/**
 *
 * @author  ‘åàV‹`‘é
 */
public class NewJFrame2 extends javax.swing.JFrame {
  
  /** Creates new form NewJFrame2 */
  public NewJFrame2() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    aspectCombinationPanel1 = new to.tetramorph.starbase.chartparts.AspectCombinationPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().add(aspectCombinationPanel1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new NewJFrame2().setVisible(true);
      }
    });
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private to.tetramorph.starbase.chartparts.AspectCombinationPanel aspectCombinationPanel1;
  // End of variables declaration//GEN-END:variables
  
}
