/*
 * NewJFrame.java
 *
 * Created on 2007/09/19, 2:07
 */

package to.tetramorph.starbase.chartmodule;

import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  ‘åàV‹`‘é
 */
public class NewJFrame extends javax.swing.JFrame {
  
  /** Creates new form NewJFrame */
  public NewJFrame() {
    initComponents();
  }
//  private final int mci = ((Integer)Toolkit.getDefaultToolkit().getDesktopProperty("awt.multiClickInterval")).intValue();
//  private boolean flag;
//  public void mouseClicked(MouseEvent evt) {
//    int count = evt.getClickCount();
//    if(count == 1) {
//      new Thread(new Runnable() {
//        public void run() {
//          flag = true;
//          try { Thread.sleep(mci); } catch (InterruptedException e) {}
//          if (flag) {
//            //ŽlŠp‚ð•`‰æ
//          }
//        }
//      }).start();
//    } else if(count == 2) {
//      flag = false;
//      //ŽOŠp‚ð•`‰æ
//    }
//  }
  
  void test() {
    JOptionPane pane = new JOptionPane();
    JInternalFrame dialog =
      pane.createInternalFrame(jDesktopPane1, "HogeHoge");
    //pane.selectInitialValue();
    dialog.setLayout(new GridLayout(0,1));
    dialog.add(jPanel2);
    dialog.setVisible(true);
    
        /* Since all input will be blocked until this dialog is dismissed,
         * make sure its parent containers are visible first (this component
         * is tested below).  This is necessary for JApplets, because
         * because an applet normally isn't made visible until after its
         * start() method returns -- if this method is called from start(),
         * the applet will appear to hang while an invisible modal frame
         * waits for input.
         */
//    if (dialog.isVisible() && !dialog.isShowing()) {
//      Container parent = dialog.getParent();
//      while (parent != null) {
//        if (parent.isVisible() == false) {
//          parent.setVisible(true);
//        }
//        parent = parent.getParent();
//      }
//    }
  }
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel2 = new javax.swing.JPanel();
    jButton2 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jButton3 = new javax.swing.JButton();
    jComboBox1 = new javax.swing.JComboBox();
    jDesktopPane1 = new javax.swing.JDesktopPane();
    jPanel1 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();

    jPanel2.setLayout(new java.awt.GridBagLayout());

    jButton2.setText("jButton2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    jPanel2.add(jButton2, gridBagConstraints);

    jLabel1.setText("jLabel1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    jPanel2.add(jLabel1, gridBagConstraints);

    jButton3.setText("jButton3");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    jPanel2.add(jButton3, gridBagConstraints);

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    jPanel2.add(jComboBox1, gridBagConstraints);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

    jButton1.setText("TEST");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jPanel1.add(jButton1);

    getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents
  
  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    test();
  }//GEN-LAST:event_jButton1ActionPerformed
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new NewJFrame().setVisible(true);
      }
    });
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JComboBox jComboBox1;
  private javax.swing.JDesktopPane jDesktopPane1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  // End of variables declaration//GEN-END:variables
  
}
