/*
 * PopupTestPanel.java
 *
 * Created on 2007/09/19, 19:42
 */

package to.tetramorph.starbase.chartmodule;

/**
 *
 * @author  ‘åàV‹`‘é
 */
public class PopupTestPanel extends javax.swing.JPanel {
  
  /** Creates new form PopupTestPanel */
  public PopupTestPanel() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jPanel1 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox();

    setLayout(new java.awt.BorderLayout());

    jButton1.setText("OK");
    jPanel1.add(jButton1);

    jButton2.setText("NG");
    jPanel1.add(jButton2);

    add(jPanel1, java.awt.BorderLayout.SOUTH);

    jPanel2.setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("TEST");
    jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jPanel2.add(jComboBox1, new java.awt.GridBagConstraints());

    add(jPanel2, java.awt.BorderLayout.CENTER);

  }// </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JComboBox jComboBox1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  // End of variables declaration//GEN-END:variables
  
}
