/*
 * TimeSliderDialog.java
 *
 * Created on 2006/10/11, 1:56
 */

package to.tetramorph.starbase;

import javax.swing.SwingUtilities;

/**
 * TimeSliderPanelがはめこまれるモーダレスのダイアログ
 */
class TimeSliderDialog extends javax.swing.JDialog {
  private TimeSliderPanel timeSliderPanel;
  /** 
   * @param 親となるフレームオブジェクト
   */
  public TimeSliderDialog(java.awt.Frame parent) {
    super(parent, false);
    initComponents();
    WindowMoveHandler winmove = new WindowMoveHandler("TimeSliderDialog.BOUNDS", this);
    addComponentListener(winmove);
    winmove.setBounds();
    this.setTitle("時間リモコン");
    pack();
  }
  /**
   * ダイアログ内のTimeSliderPanelを返す。
   */
  public TimeSliderPanel getTimeSliderPanel() {
    return timeSliderPanel;
  }
  /**
   * ダイアログにTimeSliderPanelをセットする。
   */
  public void setTimeSliderPanel(TimeSliderPanel panel) {
    assert SwingUtilities.isEventDispatchThread(): "Not EDT";
    assert panel != null:"null禁止";
    if(timeSliderPanel == panel) return; //同じものは再セットしない
    removeTimeSliderPanel();
    add(panel);
    pack();
    validate();
    repaint();
    timeSliderPanel = panel;
    System.out.println("タイムスライダーセット");
  }
  /**
   * ダイアログからTimeSliderPanelを削除する。
   */
  public void removeTimeSliderPanel() {
    assert SwingUtilities.isEventDispatchThread(): "Not EDT";
    if(timeSliderPanel == null) return;
    this.remove(timeSliderPanel);
    getLayout().removeLayoutComponent(timeSliderPanel);
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    getContentPane().setLayout(new java.awt.GridLayout(1, 0));

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    dispose();
  }//GEN-LAST:event_formWindowClosing
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
  
}
